version: 2.1

orbs:
  node: circleci/node@4.4.0

defaults: &defaults
  working_directory: ~/repo
  environment:
    GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1

executors:
  linux:
    <<: *defaults
    docker:
      - image: circleci/node:14
  windows:
    <<: *defaults
    docker:
      - image: circleci/windows@2.4.0
  macos:
    <<: *defaults
    macos:
      xcode: &_XCODE_VERSION '12.5.0'

commands:
  setup:
    parameters:
      os:
        type: string
    steps:
      - checkout
      - when:
          condition:
            equal: [<< parameters.os >>, macos]
          steps:
            - node/install:
                node-version: '14.17.0'
                install-yarn: true
            - run: node --version
            - run: sudo gem install cocoapods
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - nrwl-nx-yarn-packages-<< parameters.os >>-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          # Windows needs its own cache key because binaries in node_modules are different.
          key: nrwl-nx-yarn-packages-<< parameters.os >>-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  checks-and-unit-tests:
    parameters:
      os:
        type: string
        default: 'linux'
    executor: << parameters.os >>
    steps:
      - setup:
          os: << parameters.os >>
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run Unit Tests
          command: yarn test
  end-to-end-tests:
    parameters:
      os:
        type: string
        default: 'macos'
    executor: << parameters.os >>
    steps:
      - setup:
          os: << parameters.os >>
      - run: npm install -g detox-cli
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run:
          name: Build
          command: yarn build
          no_output_timeout: 30m
      - run:
          name: E2E
          command: yarn e2e
          no_output_timeout: 30m

workflows:
  build:
    jobs:
      - checks-and-unit-tests
      - end-to-end-tests:
          matrix:
            parameters:
              os: ['macos']
